### ISSUE TITLE
End to End Machine learning with Snowflake and Dataiku - No Knoema Labor Data Atlas in MarketPlace

### ISSUE THREAD

**Issue by JRabida** [Snowflake-Labs/sfquickstarts#1037]
**Describe the bug**
I'm doing the tutorial 'End to End Machine learning with Snowflake and Dataiku
https://quickstarts.snowflake.com/guide/end_to_end_machine_learning_with_dataiku/index.html#3
Step 4 - Load into SnowFlake
section - 5 - Adding unemployment data from Marketplace.
I can't find an option for Knoema Labor Data Atlas in the MarketPlace

**Comment by stevewithington** [comment]
@JRabida, see <https://github.com/Snowflake-Labs/sfquickstarts/issues/990#issuecomment-1909121883>

**Comment by JRabida** [comment]
Closing issue, duplicate of #990 commented above. 
Thank you, @stevewithington
