### ISSUE TITLE
Snowflake_Python_API Quickstart lab

### ISSUE THREAD

**Issue by ckarkhan** [Snowflake-Labs/sfquickstarts#1200]
**Describe the bug**
Error in cell #7  that creates a new table called "**PYTHON_API_TABLE**", the cell errors out with the error

**TypeError: BaseModel.__init__() takes 1 positional argument but 3 were given**

`table = schema.tables.create(Table(
        name="PYTHON_API_TABLE", 
        columns=[TableColumn("TEMPERATURE", "int", nullable=False), TableColumn("LOCATION", "string")],
    ), 
    mode="orreplace")
`

The earlier cells that create a database and schema run okay.

**URL of where you see the bug**
It's on my mac running Jupyter in VS Code.

**To Reproduce**
1. Go to ' getting_started_snowflake_python_api_ipynb' notebook

**Expected behavior**

**Screenshots**

![image](https://github.com/Snowflake-Labs/sfquickstarts/assets/15005236/ee5c524f-4d7c-42ab-bb0b-e02bf5b08c1f)

**Desktop (please complete the following information):**
 - OS:MacOS Ventura 13.6.6

**Smartphone (please complete the following information):**

**Additional context**
I am running a jupyter notebook in VS Code.  getting_started_snowflake_python_api_ipynb

**Comment by ckarkhan** [comment]
Any and all pointers are appreciated!

**Comment by sfc-gh-ghernandez** [comment]
> Any and all pointers are appreciated!

Thanks @ckarkhan – the Notebook and Quickstart have been updated! Please let us know if you run into anymore issues.
