### ISSUE TITLE
DirectQuery.pbit missing from "Attaining Consumer Insights with Snowflake and Microsoft Power BI"

### ISSUE THREAD

**Issue by huidarin** [Snowflake-Labs/sfquickstarts#121]
In Step 7 of the guide for the virtual hands-on lab "Attaining Consumer Insights with Snowflake and Microsoft Power BI", it instructs us to open the file DirectQuery.pbit. However, this file cannot be located anywhere on the guide or on GitHub. The instructors stated that it would be made available for us.

Please let me know where I can download this file to complete the lab!

Thanks

**Comment by sfc-gh-jwest** [comment]
Added a download link for the PBI file
