### ISSUE TITLE
Git repository for the quickstart "Getting Started with Document AI" not found

### ISSUE THREAD

**Issue by psaenzdetejada** [Snowflake-Labs/sfquickstarts#1298]
**Describe the bug**
The link to the git repository https://github.com/Snowflake-Labs/sfguide-getting-started-with-document-ai for the Getting Started with Document AI is broken.

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/getting_started_with_document_ai/index.html?index=..%2F..index#0

**To Reproduce**
1. Go to 'https://quickstarts.snowflake.com/guide/getting_started_with_document_ai/index.html?index=..%2F..index#0'
2. Click on 'Clone or download the git repo'
4. See error: the link is broken

**Expected behavior**
A correct link to a gir repository

**Comment by iamontheinet** [comment]
@psaenzdetejada Thanks for flagging. The repo should be Public now.

**Comment by psaenzdetejada** [comment]
That was fast! Thanks @iamontheinet
