### ISSUE TITLE
Tour of Ingest

### ISSUE THREAD

**Issue by sfc-gh-jdority** [Snowflake-Labs/sfquickstarts#1308]
**Describe the bug**
faker.optional throws error:
Traceback (most recent call last):
  File "/Users/jdority/src/tour_of_ingest/./data_generator.py", line 44, in <module>
    print_lift_ticket()
  File "/Users/jdority/src/tour_of_ingest/./data_generator.py", line 34, in print_lift_ticket
    'phone': fake.optional(fake.phone_number())
TypeError: 'OptionalProxy' object is not callable

**URL of where you see the bug**
Test Data Generator
https://quickstarts.snowflake.com/guide/tour_of_ingest/index.html?index=..%2F..index#2

**To Reproduce**
Try to execute the code and you will experience

**Expected behavior**
Cutting and pasting the quickstart code should work.  :-)

**Additional context**
[Add any other context about the problem here.]

https://pypi.org/project/optional-faker/
Note that faker added own optional proxy, which however can be used only with callables. This is why in version 2.0.0 we renamed our method to none_or.

If I replace optional with none_or method, the code works as advertised.

**Comment by sfc-gh-bculberson** [comment]
fixed in #1585
