### ISSUE TITLE
Typo "Aggrigations" in step 6.3 title

### ISSUE THREAD

**Issue by sfc-gh-mabrennan** [Snowflake-Labs/sfquickstarts#131]
**Describe the bug**
In "Attaining Consumer Insights with Snowflake and Microsoft Power BI" quickstart there is a typo "Aggrigations" in step 6.3 title

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/attaining_consumer_insights_with_snowflake_and_microsoft_power_bi/index.html?index=..%2F..in

**Comment by jdanielmyers** [comment]
fix pushed -- thank you!
