### ISSUE TITLE
Step 6: dbt_utils version should be 0.7.0 for dbt version 0.20.2 and for specified 0.6.4 the dbt version 0.20.2 is not compatible

### ISSUE THREAD

**Issue by vaddeh** [Snowflake-Labs/sfquickstarts#132]
Step 6: dbt_utils version should be 0.7.0 for dbt version 0.20.2 and for specified 0.6.4 the dbt version 0.20.2 is not compatible

**Comment by jdanielmyers** [comment]
Hi Vaddeh, can you please provide the URL where you see this? We have many quickstarts and need to know which one you are referencing. Thank you!

**Comment by jdanielmyers** [comment]
Hi @vaddeh we've done a major overhaul of the dbt. this should be all fixed - thank you!
