### ISSUE TITLE
Whoever created this workthrough is an absolute moron. No instructions given on how to connect dbt to snowflake in profile.yml. DIrectly ran the DAGs. Pictures of files/directory are absolutely wrong at some places.

### ISSUE THREAD

**Issue by rajdeepUOB** [Snowflake-Labs/sfquickstarts#1333]
**Describe the bug**

**URL of where you see the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimnicholls** [comment]
Whoever created this issue is an absolute moron. No reference to what they're actually referring to. The subject is just a rant. No attempt was made at all at completing the issue template.

But, I do hope they feel better now now they've vented.

**Comment by iamontheinet** [comment]
N/A

**Comment by rajdeepUOB** [comment]
@jimnicholls Cant you figure out from the subject line itself? I am talking about the dbt connection with snowflake. The walkthrough doesn't show that. Even the connection of Snowflake with Airflow. Its missing. And also some images are inconsistent . 
<img width="291" alt="i1" src="https://github.com/Snowflake-Labs/sfquickstarts/assets/132142685/0d659804-23f0-4f9d-b5de-e212842026ce">
![i2](https://github.com/Snowflake-Labs/sfquickstarts/assets/132142685/bb00d585-71ce-4168-b018-0b90c259f56d)
![i3](https://github.com/Snowflake-Labs/sfquickstarts/assets/132142685/7ba40fd0-66d3-44ba-bc48-cfa0d099e4a8)

The files are supposed to be in the 'Cosmosproject' directory, if you can read the walkthrough. For a beginner it becomes difficult to follow if the walkthrough lacks parity.

And whenever a dbt connection is created with snowflake, like, when you run the command 'dbt init', you are prompted with selecting  database (snowflake, bigquery etc) and also the database name, role name, warehouse name, account info etc. The walkthrough misses these parts. 


I can go on but are these issues good enough for you? Or will you be more sarcastic?
