### ISSUE TITLE
Link to notebook broken in Cortex tutorial

### ISSUE THREAD

**Issue by jane-delaney** [Snowflake-Labs/sfquickstarts#1375]
Link to notebook in this tutorial doesn't work: https://quickstarts.snowflake.com/guide/customer_reviews_analytics_using_snowflake_cortex/index.html?index=..%2F..index#2 Can't find notebook in repo, has it been taken down?

**Comment by iamontheinet** [comment]
@jane-delaney Please try it now. It should be available. Thanks for flagging.
