### ISSUE TITLE
Add Note About PDF Structure on Quickstart: Build a Retrieval Augmented Generation (RAG) based LLM assistant using Streamlit and Snowflake Cortex

### ISSUE THREAD

**Issue by sfc-gh-space** [Snowflake-Labs/sfquickstarts#1432]
**Describe the improvement**
In step two of this RAG Quickstart, it should be made clear that the PDFs have to be in text format. I think we need to add the following text at the bottom of step one:

**NOTE:** This Quickstart uses the PyPDF library to extract text from the documents above. If you swap out these documents with others, make sure they are text based PDFs. If you have scanned PDFs (e.g. images), you will need to add a step to convert the image to text using a library like tesserocr.

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/asking_questions_to_your_own_documents_with_snowflake_cortex/index.html?index=..%2F..index#1

**To Reproduce**
If you try to process a scanned PDF with no text, the output of the pdf_text_chunker process will be NULL (as expected). 

**Expected behavior**
Longer term, we could modify the pdf_text_chunker function to add functionality to extract text from images as well. 

If <PDF is already text> extract text and chunk it, else
If <PDF is image>, OCR to text then chunk it, else
Return "No text found"

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by dcvaughn** [comment]
+1

**Comment by mahanteshimath** [comment]
If pdf contains image(with text) it does not work properly

**Comment by iamontheinet** [comment]
Added this note:

NOTE: This Quickstart uses the PyPDF library to extract text from the documents above. If you swap out these documents with others, make sure they are text based PDFs. For example, if you have scanned PDFs (e.g. images), you will need to add a step to convert the image to text using a library like tesserocr. Similarly, if you have password protected PDFs, you will need to use a different Python library.
