### ISSUE TITLE
Dataiku HoL now creates bad models because Peru reported bad data

### ISSUE THREAD

**Issue by sfc-gh-sweingartner** [Snowflake-Labs/sfquickstarts#154]
**Describe the bug**
The HoL "Accelerating Data Science with Snowflake and Dataiku" used to work great where users can go to the Snowflake Marketplace, get some John Hopkins Covid data then build and score models in Dataiku.  This HoL now produces really bad models.  The underlying problem is that the data has changed with time and the solution doesn't deal with some really bad data coming out of Peru on June 3 2021.

**URL of where you see the bug**
Any instance of dataiku.  

**To Reproduce**
1. Follow the steps of this hands on lab:  https://quickstarts.snowflake.com/guide/data_science_with_dataiku/index.html?index=..%2F..index#0

**Expected behavior**
On this chapter of the lab, https://quickstarts.snowflake.com/guide/data_science_with_dataiku/index.html?index=..%2F..index#5 you can scroll to where it says "Drilldown into the details of the best performing model". Typically, the models are somewhere around .6 to .9 ROC score.  They are now about a 0.1 which means it's about as accurate as flipping a coin.  

I supposed that data drifted and the models went stale.  So, by adding filters, I determined that the solution works great if we filter earlier than a certain date.   The date that causes all the problems is 2 June.   If we break that problem out by country, we can see that Peru reported tons of deaths on that date but didn't assign a State.  Then on 3 June they assigned a State for all the deaths.  As the solution subtracts each day from the other to see the changes, there are tons of negative deaths on 2 June then tons of more negative deaths on June 3.  There shouldn't be an extraordinary number of negative death counts.  Just a normal number of positive death counts.  

**Screenshots**
Here is the problem with the underlying data:  
I have images but GIT doesn't seem to allow me to embed or attach images

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I was able to fix the problem by adding a filter as my first step in the lab to filter out where the country is Peru.  Another solution would be to delete all the weird death counts from Peru for 2 June and replace it with the identical data from 1 June or 3 June.

**Comment by sfc-gh-sweingartner** [comment]
Update.  I've shared a fix in a Google Doc with @sfc-gh-jwest

**Comment by sfc-gh-madkins** [comment]
@stephenweingartner @sfc-gh-jwest  is this issue resolved? Is there a PR you submitted?

**Comment by sfc-gh-sweingartner** [comment]
Yes.  This is resolved and can be closed.

Regards,
Stephen


STEPHEN WEINGARTNER
Senior Solution Engineer

MOBILE  +61 405 365 180
EMAIL  ***@***.*** ***@***.***>


Snowflake Inc.
699 Collins Street, Level 8
Melbourne, VIC 3000
Australia

***@***.***>
