### ISSUE TITLE
A Comprehensive Guide: Ingesting Data into Snowflake

### ISSUE THREAD

**Issue by sfc-gh-ffoo** [Snowflake-Labs/sfquickstarts#1540]
**Describe the bug**
Please update the conda environment.yml file 
As well as the test data generation data_generator.py file, optional-faker method has changed from using optional to none_or

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/a_comprehensive_guide_to_ingesting_data_into_snowflake/index.html?index=..%2F..index#2

**To Reproduce**
1. Creating the conda environment will fail as dependencies such as openJDK cannot be resolved
2. Running the test data generator will fail as optional-faker cannot call the optional method anymore

**Comment by sfc-gh-bculberson** [comment]
fixed in https://github.com/Snowflake-Labs/sfquickstarts/pull/1585
