### ISSUE TITLE
Error Loading Data Step #5 in Getting Started with Snowflake - Zero to Snowflake

### ISSUE THREAD

**Issue by csapoche** [Snowflake-Labs/sfquickstarts#156]
When running the copy into trips from @citibike_trips file_format=CSV; (4.2.2) command from worksheet, getting the following error:

Numeric value '' is not recognized File 'citibike-trips/trips_2014_0_5_0.csv.gz', line 39, character 168 Row 39, column "TRIPS"["BIRTH_YEAR":15] If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.

**Comment by sfc-gh-jwest** [comment]
@csapoche make sure your CSV file format is configured exactly as it is in the lab screen shot.  I just stepped through the lab, and I was able to load the data.
