### ISSUE TITLE
SSH Keys creation using terraform

### ISSUE THREAD

**Issue by nujiel** [Snowflake-Labs/sfquickstarts#163]
**Describe the bug**
When deploying a user using the terraform method, the key is not using pkcs#8 which brings an error:
-  using jdbc connector:"Private key provided is invalid or not supported"
-  using snowsql: "Failed to load private key: Private key provided is not in PKCS#8 format".

After manually converting the private ssh key generated by terraform, i got the following error: "250001 (08001): Failed to connect to DB: XXXXX.YYYY.azure.snowflakecomputing.com:443. JWT token is invalid."

I resolved it by altering the terraform generated user in Snowflake and inserting the public key as a one liner and without the "-----BEGIN PUBLIC KEY-----" and "-----END PUBLIC KEY-----".

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/terraforming_snowflake/index.html?index=..%2F..index#8

**To Reproduce**
Apply the documentation with terraform.

**Expected behavior**
Deploy a user with the correct public key in snowflake and have the private key in the right format from terraform.

**Desktop (please complete the following information):**
 - OS: Mac OS Big 1.6
 - Terraform: 1.0.9
 - registry.terraform.io/chanzuckerberg/snowflake: 0.25.22

**Additional context**
Terraform user configuration:

resource "snowflake_user" "joe" {
    provider          = snowflake.security_admin
    name              = "joe-bot"
    default_role      = "CREATE_ROLE"
    default_namespace = "DB.PUBLIC"
    rsa_public_key    = substr(tls_private_key.joe_key.public_key_pem, 27, 398)
}

**Comment by nujiel** [comment]
Hello
the commit does solve an issue in the documentation for the terraform user but not for the creation of users via terraform.

**Comment by sfc-gh-jwest** [comment]
@nujiel can you provide some details around how users are created via terraform?
