### ISSUE TITLE
Unavailable tables

### ISSUE THREAD

**Issue by carlohakkoda1** [Snowflake-Labs/sfquickstarts#176]
I'm currently working with the dbt lab for snowflake and I have some issues relate to the tables. The database: "KNOEMA_ECONOMY_DATA_ATLAS" on the dbt lab works with the tables "exratescc2018" and "usindssp2020", but in the moment that I got this database on the marketplace, it didn't include those tables.

This a screenshot from the dbt lab:
![Screen Shot 2021-11-12 at 09 55 06](https://user-images.githubusercontent.com/94186895/141496088-a1b5488e-16c4-4974-b150-5ea3770ce95e.png)

That are the tables that I got from "KNOEMA_ECONOMY_DATA_ATLAS" database:
![image](https://user-images.githubusercontent.com/94186895/141496320-2e42d770-10d1-461d-ab22-b99124ae93e3.png)

**Comment by sfc-gh-jwest** [comment]
@carlohakkoda1 the extraescc2018 and usindssp2020 are views in that database.
If you expand the 'Views' you should see them.  Let me know if you are unable to see them, or if you are getting an error.

**Comment by carlohakkoda1** [comment]
Yes, I know that they are a views, but the problem is there is a moment
that I call them as table not as a views, and that moment, dbt give me a
error

**Comment by sfc-gh-jwest** [comment]
@carlohakkoda1 does the error state that the usindssp2020 view was defined as 12 columns, but the view query returns 13 columns?

**Comment by carlohakkoda1** [comment]
I will do the lab again because honestly I did it last week and I didnt
remember the error the dbt gave me.

But I think that it is a compilation error. (I'm not sure).

**Comment by carlohakkoda1** [comment]
This is a first error that I got it:

How it's supposed to be:

[image: image.png]

What I got:
[image: image.png]
