### ISSUE TITLE
Database Error in model stg_knoema_stock_history

### ISSUE THREAD

**Issue by nervuzz** [Snowflake-Labs/sfquickstarts#177]
**Describe the bug**
There is some issue with the 'usindssp2020 ' view from 'Knoema Economy Data Atlas' data source that makes it impossible to finish the lab.

**To Reproduce**
1. Go to https://quickstarts.snowflake.com/guide/data_engineering_with_dbt/#7
2. Follow lab steps until 'stg_knoema_stock_history.sql' is saved with code from provided snippet
2. Click on 'Preview' button
3. See error

**Expected behavior**
- Query results returned

**Screenshots**
![obraz_2021-11-16_225812](https://user-images.githubusercontent.com/15368390/142072578-80fbbc98-4bde-4bbe-9247-cfb9592ef792.png)

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Opera
 - Version: 80.0.4170.63

**Additional context**
- dbt Cloud v1.1.39.11
- dbt version 0.21.0
- data source connected to Snowflake on 2021-11-16

**Comment by sfc-gh-jwest** [comment]
Knoema has fixed the view.

**Comment by Gregory-Clark** [comment]
Just imported the database, again, to continue the lab. It is not fixed.

SQL compilation error: View definition for 'KNEOMA_ECONOMY_DATA_ATLAS.ECONOMY.USINDSSP2020' declared 13 column(s), but view query produces 12 column(s).
