### ISSUE TITLE
Accelerating Data Teams with dbt & Snowflake: Database error when querying KNOEMA_ECONOMY_DATA_ATLAS.ECONOMY.USINDSSP2020

### ISSUE THREAD

**Issue by syed-a-ali** [Snowflake-Labs/sfquickstarts#178]
**Describe the bug**
In lab `Accelerating Data Teams with dbt & Snowflake` following error occurs when querying view `KNOEMA_ECONOMY_DATA_ATLAS.ECONOMY.USINDSSP2020`.

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/data_engineering_with_dbt/index.html?index=..%2F..index&mkt_tok=MjUyLVJGTy0yMjcAAAGAw7qDQkpiA_IARtqZyzNTwfvNesrTfAZ-VHnyCnDIA1Zb8AiIsoz3v5YhR1-KvSQIraAX-3rZgxfomASLghicVW6ocF49SDgoPemuNB9nzNsTiOY#3

**To Reproduce**
1. Go to '[Step 4 of Lab](https://quickstarts.snowflake.com/guide/data_engineering_with_dbt/index.html?index=..%2F..index&mkt_tok=MjUyLVJGTy0yMjcAAAGAw7qDQkpiA_IARtqZyzNTwfvNesrTfAZ-VHnyCnDIA1Zb8AiIsoz3v5YhR1-KvSQIraAX-3rZgxfomASLghicVW6ocF49SDgoPemuNB9nzNsTiOY#3)'
2. Scroll down to step where following query needs to be run:
```
select * 
  from KNOEMA_ECONOMY_DATA_ATLAS.ECONOMY.USINDSSP2020
 where "Date" = current_date();
```
3. Run the query in Snowflake console
4. See error: 
```
View definition for 'KNOEMA_ECONOMY_DATA_ATLAS.ECONOMY.USINDSSP2020' declared 12 column(s), but view query produces 13 column(s).
```
**Expected behavior**
Query should return data.

**Screenshots**
![Screen Shot 2021-11-17 at 3 47 46 PM](https://user-images.githubusercontent.com/68348391/142287764-075c876f-64fa-40ff-932b-d0e8449f8c61.png)

**Desktop (please complete the following information):**
 - OS: macOS Version 10.15.7 (Build 19H1419)
 - Browser: Chrome
 - Version: 95.0.4638.69 (Official Build) (x86_64)

**Comment by sfc-gh-jwest** [comment]
Thank you @syed-a-ali, we already have an issue open for this (#177).  We have requested that Knoema fix the view.
