### ISSUE TITLE
secure view has changed

### ISSUE THREAD

**Issue by sfc-gh-mlindl** [Snowflake-Labs/sfquickstarts#181]
Has the underlying view changed? can you please assist as this is a secure view

dbtcli-snowflake % dbt run --model l10_staging --no-version-check
Running with dbt=0.21.0
[WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.dbtcli_snowflake.l30_mart
- models.dbtcli_snowflake.l20_transform

Found 2 models, 0 tests, 0 snapshots, 0 analyses, 359 macros, 0 operations, 0 seed files, 2 sources, 0 exposures

00:29:02 | Concurrency: 200 threads (target='dev')
00:29:02 | 
00:29:02 | 1 of 2 START view model l10_staging.base_knoema_fx_rates............. [RUN]
00:29:02 | 2 of 2 START view model l10_staging.base_knoema_stock_history........ [RUN]
00:29:04 | 2 of 2 ERROR creating view model l10_staging.base_knoema_stock_history [ERROR in 1.98s]
00:29:04 | 1 of 2 OK created view model l10_staging.base_knoema_fx_rates........ [SUCCESS 1 in 2.10s]
00:29:04 | 
00:29:04 | Finished running 2 view models in 5.12s.

Completed with 1 error and 0 warnings:

Database Error in model base_knoema_stock_history (models/l10_staging/base_knoema_stock_history.sql)
  002057 (42601): SQL compilation error:
  View definition for 'KNOEMA_ECONOMY_DATA_ATLAS.ECONOMY.USINDSSP2020' declared 12 column(s), but view query produces 13 column(s).
  compiled SQL at target/run/dbtcli_snowflake/models/l10_staging/base_knoema_stock_history.sql

Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2

**Comment by sfc-gh-jwest** [comment]
This has been resolved.  Knoema fixed the view definition.
