### ISSUE TITLE
https://github.com/brenStokes/Building-an-App-with-Data-Marketplace-/tree/main/quasar

### ISSUE THREAD

**Issue by psabela** [Snowflake-Labs/sfquickstarts#183]
This link is not working:
https://github.com/brenStokes/Building-an-App-with-Data-Marketplace-/tree/main/quasar

Source where this link is referenced: 
https://quickstarts.snowflake.com/guide/vhol_data_marketplace_app/index.html?index=..%2F..index#3

**Comment by jdanielmyers** [comment]
Thanks - a pr has been merged
