### ISSUE TITLE
Spelling mistakes - collated into single issue

### ISSUE THREAD

**Issue by VasuBajaj** [Snowflake-Labs/sfquickstarts#231]
Page: https://quickstarts.snowflake.com/guide/getting_started_with_snowflake/index.html?index=..%2F..index#4
section - Create a New Warehouse for Data Analytics
![image](https://user-images.githubusercontent.com/41167055/158531589-e916d837-57aa-4de4-a02a-723a2d4f9865.png)

Page: https://quickstarts.snowflake.com/guide/getting_started_with_snowflake/index.html?index=..%2F..index#6 
section: Create a New Database and Table for the Data
tto -> to

![image](https://user-images.githubusercontent.com/41167055/158531296-f629b9c0-7ac7-44d0-acfe-19a152d5bfec.png)

Page: https://quickstarts.snowflake.com/guide/getting_started_with_snowflake/index.html?index=..%2F..index#8
section: Create a New Role and Add a User

![image](https://user-images.githubusercontent.com/41167055/158533633-e3338c75-5e8d-4cfe-a8eb-34d52340242e.png)

**Comment by djames42** [comment]
Page 3, Section "Roles": tablular -> tabular
Page 4, Section "Create an External Stage": buttion -> button
