### ISSUE TITLE
Looker Screenshots in Guides

### ISSUE THREAD

**Issue by gostrer** [Snowflake-Labs/sfquickstarts#31]
We've got a Looker report screenshot in the resource optimization guide. 
https://guides.snowflake.com/guide/resourceoptimization-billingmetrics/index.html?index=..%2F..index#2

It's also labeled Cumulative Revenue, we may want to label it different when we change to Tableau or Snowsight (ideally) as the image.

**Comment by mmeredith911** [comment]
Good points Daniel - thank you! I'll be sure to get these updated soon.
