### ISSUE TITLE
Section Numbering in Zero 2 Snowflake Guide vs. SQL script

### ISSUE THREAD

**Issue by sfc-gh-tmustafic** [Snowflake-Labs/sfquickstarts#32]
Hi team,

I just came across that the numbering of sections differ in the Zero 2 Snowflake public guide and the corresponding SQL script: 

- In the public guide ([Link](https://guides.snowflake.com/guide/getting_started_with_snowflake/index.html?index=..%2F..index#3)): 4. Preparing to Load Data 
- In the SQL script ([Link](https://s3.amazonaws.com/snowflake-workshop-lab/lab_scripts_OnlineZTS.sql)): Module 3 (3.x.x)

I think that this also has an impact on subsequent numbering of sections.

**Comment by jdanielmyers** [comment]
Thank you for bringing this to our attention! We will get it fixed and updated.

**Comment by sfc-gh-jwest** [comment]
Working on this now.  I am going to embed all the sql in the guide, and remove the need to download the sql script.

**Comment by sfc-gh-jwest** [comment]
Resolved

**Comment by sfc-gh-jwest** [comment]
Removed the downlad sql section, all sql is imbedded in the lab guide.
