### ISSUE TITLE
UDF to convert Kelvin to Celcius in training exercise, is formula to convert Fahrenheit to Celcius not Kelvin to Celcius

### ISSUE THREAD

**Issue by Garschke** [Snowflake-Labs/sfquickstarts#330]
-- UDF to convert Kelvin to Celcius
-- *** is actually the formula to convert Fahrenheit to Celcius ***
use database vhol_database;
use schema vhol_schema;
use warehouse VHOL_WH;
create or replace function degFtoC(k float)
returns float
as
$$
  truncate((k - 32) * 5/9, 2)
$$;

**Comment by jdanielmyers** [comment]
thank you for the info! fixed.
