### ISSUE TITLE
Dead link in Machine Learning with Snowpark Python

### ISSUE THREAD

**Issue by sfc-gh-fvandortmont** [Snowflake-Labs/sfquickstarts#379]
**Describe the bug**
Link points to 
https://github.com/Snowflake-Labs/sfguide-citibike-ml-snowpark-python/blob/main/00-Setup.ipynb, should point to https://github.com/Snowflake-Labs/sfguide-citibike-ml-snowpark-python/blob/main/00_Setup.ipynb

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/machine_learning_with_snowpark_python/index.html?index=..%2F..index#2

**To Reproduce**
1. Go to 'https://quickstarts.snowflake.com/guide/machine_learning_with_snowpark_python/index.html?index=..%2F..index#2'
2. Click on 'Then, open up the [00-Setup](https://github.com/Snowflake-Labs/vhol-citibike-ml-snowpark-python/blob/main/00-Setup.ipynb) Jupyter'

**Expected behavior**
Opening the notebook

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome 
 - Version 105.0.5195.102

**Comment by jdanielmyers** [comment]
thanks for the heads up! a fix has been pushed
