### ISSUE TITLE
Upgrading to v3 with a Mac

### ISSUE THREAD

**Issue by sfc-gh-sweingartner** [Snowflake-Labs/sfquickstarts#39]
I have a Mac.  2.7 is installed by default.  I go to the Python website to install 3.9.4 using the installer.  It installs.  Going forward, I don't use python or pip.  I need to use python3 or pip3 or do something like create an alias if all commands are going to use python. You may want to mention which way to go.

**Comment by jdanielmyers** [comment]
Can you please provide a link to the guide you had this issue with? Thanks!
