### ISSUE TITLE
How to run on a mac

### ISSUE THREAD

**Issue by sfc-gh-sweingartner** [Snowflake-Labs/sfquickstarts#40]
I'm new to a Mac.  Took me an hour to figure this out...
Mac users using terminal should add variables to ~/.zshenv.   (e.g. export AWSPASS=123456). 
The code also needed import os at the top to run in terminal

**Comment by jdanielmyers** [comment]
Can you please provide a link to the guide you had this issue with? Thanks!

**Comment by sfc-gh-sweingartner** [comment]
Hi Daniel, sorry.  I've done soooo many labs and trainings since starting I don't know which one that is.  I'm pretty sure it would be whereever we learn how to install SnowSQL and use that.  I don't know which quick start guide covers that.  That guide would say to modify the .profile but Mac's ZSH terminal doesn't use that.  It uses .zshenv
