### ISSUE TITLE
lab uses a mix of con and conn

### ISSUE THREAD

**Issue by sfc-gh-sweingartner** [Snowflake-Labs/sfquickstarts#41]
we create a connection conn but later on the statements switch over to con and don't run

**Comment by jdanielmyers** [comment]
Can you please provide a link to the guide you had this issue with? Thanks!

**Comment by jdanielmyers** [comment]
Closing for now since we don't know which guide this is for. Thanks!

**Comment by sfc-gh-mabrennan** [comment]
This seems to be for Getting Started with Python quickstart at https://quickstarts.snowflake.com/guide/getting_started_with_python/index.html#3

I think you should consider reopening this issue. In steps 4 to 11 it does switch (wrongly) between conn and con. I found this by using grep.
