### ISSUE TITLE
Getting Started with Unstructured Data step #8: broken formatting

### ISSUE THREAD

**Issue by sfc-gh-vtimofeenko** [Snowflake-Labs/sfquickstarts#434]
**Describe the bug**
On step number 8 of Getting Started with Unstructured Data the formatting is broken (see screenshot)

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/getting_started_with_unstructured_data/index.html?index=..%2F..index#7
**To Reproduce**
1. Go to the URL above
2. Scroll down to "Creating a UDF in Snowflake" header and a little lower
3. See broken formatting

**Expected behavior**
SQL and header formatting is correct

**Screenshots**
<img width="741" alt="Screen Shot 2022-11-27 at 14 28 16" src="https://user-images.githubusercontent.com/99751040/204163129-4aabe7e5-b720-415b-aa73-d6b9cdfadf55.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.6.1
 - Browser Firefox & Chrome
 - Version FF 107, Chrome 107

**Additional context**
Maybe a misaligned semicolon on [this line](https://github.com/Snowflake-Labs/sfquickstarts/blob/2a47891ed23163443fe48a67fecab1a449d5e9e2/site/sfguides/src/getting_started_with_unstructured_data/getting_started_with_unstructured_data.md?plain=1#L542) caused this?

**Comment by jdanielmyers** [comment]
thanks for the tip! we have fixed the issue!
