### ISSUE TITLE
show current region is invalid

### ISSUE THREAD

**Issue by strangemonad** [Snowflake-Labs/sfquickstarts#44]
The value of SNOWFLAKE_REGION actually needs to be set to one of the regions listed here https://docs.snowflake.com/en/user-guide/intro-regions.html for a valid account locator and DSN to be created but `current_region()` returns one of the region IDs described here https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#snowflake-region-ids

**Comment by jdanielmyers** [comment]
Hi, which guide did you have this problem with from guides.snowflake.com? Thank you!

**Comment by sfc-gh-dszmolka** [comment]
@jdanielmyers - guess it's the [DevOps: Terraforming Snowflake](https://quickstarts.snowflake.com/guide/terraforming_snowflake/index.html?index=..%2F..index#3) ? Actually, README.md also mentions
`SNOWFLAKE_REGION - Default is us-west-2, set this if your snowflake account is in a different region.`

but output of `current_region()` is like `AWS_EU_CENTRAL_1` which makes the project error out later.

Should we consider fixing the guide so it points to the [Snowflake region ID's](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#snowflake-region-ids) instead as pointed out by strangemonad , or suggest editing the output of `current_region()` or any other approach ?

**Comment by sfc-gh-dszmolka** [comment]
@jdanielmyers  - guess it's the [DevOps: Terraforming Snowflake](https://quickstarts.snowflake.com/guide/terraforming_snowflake/index.html?index=..%2F..index#3) ? Actually, README.md also mentions
SNOWFLAKE_REGION - Default is us-west-2, set this if your snowflake account is in a different region.

but output of current_region() is like AWS_EU_CENTRAL_1 which makes the project error out later. For example, an account in eu-central-1:
```
[..]
snowflake_warehouse.warehouse: Still creating... [40s elapsed]
╷
│ Error: error creating database: Post "https://myaccount.AWS_EU_CENTRAL_1.snowflakecomputing.com:443/session/v1/login-request?requestId=<requestid>f&request_guid=<requestguid>&roleName=SYSADMIN": x509: certificate is valid for *.us-west-2.snowflakecomputing.com, *.us-west-2.aws.snowflakecomputing.com, *.global.snowflakecomputing.com, *.snowflakecomputing.com, *.prod1.us-west-2.aws.snowflakecomputing.com, *.prod2.us-west-2.aws.snowflakecomputing.com, not myaccount.AWS_EU_CENTRAL_1.snowflakecomputing.com

```

Correct SNOWFLAKE_REGION would be eu-central-1 here, for `current_region() = AWS_EU_CENTRAL_1`.

Should we consider fixing the guide so it points to the [Snowflake region ID's](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#snowflake-region-ids) instead as pointed out by strangemonad , or suggest editing the output of current_region() or any other approach ?
