### ISSUE TITLE
Getting Started with Snowflake - Zero to Snowflake - Data Share issue

### ISSUE THREAD

**Issue by sfc-gh-aengelbrecht** [Snowflake-Labs/sfquickstarts#458]
**Describe the bug**
Need to click on "Create a Direct Share" not on "Publish to Specificed Consumers:"
To provide the screenshot and workflow listed on the page.

[**URL of where you see the bug**]
(https://quickstarts.snowflake.com/guide/getting_started_with_snowflake/index.html?index=..%2F..index#9)

**Comment by jdanielmyers** [comment]
thanks for the tip - fixed!
