### ISSUE TITLE
 Build A Data Clean Room Cleanroom says there is a prerequesite which can't be found

### ISSUE THREAD

**Issue by sfc-gh-sweingartner** [Snowflake-Labs/sfquickstarts#468]
**Describe the bug**
In three places on this page, it states that this is an advanced quickstart and we need to do the basic quickstart first.  The links to that basic quickstart don't work and just keep you where you are.  In searching the quickstart home page, I can only find one clean room quick start which is this "advanced" one.  

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/build_a_data_clean_room_in_snowflake_advanced/#0

**To Reproduce**
1. Go to the URL provided
2. Click on any of the three links to bring you to the basic clean room quickstart
3. Nothing happens

**Expected behavior**
Either bring the user to the basic quickstart or if that doesn't exist as a requisite anymore then remove all mentions that it is a prerequisite.  

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sfc-gh-rblum** [comment]
This issue has been fixed by removing all references to the deprecated original DCR quickstart in the new advanced quickstart.  cc: @sfc-gh-sweingartner
