### ISSUE TITLE
Unable to terraform snowflake data warehouse

### ISSUE THREAD

**Issue by leeadh** [Snowflake-Labs/sfquickstarts#50]
Hi i did as per the instructions here https://guides.snowflake.com/guide/terraforming_snowflake/index.html?index=..%2F..index#3

but I couldn't terraform. Got a 

error creating warehouse: Post "https://xxxxx.AWS_AP_SOUTHEAST_1.snowflakecomputing.com:443/session/v1/login-request?requestId=4c4c47c8-05b4-488f-be6a-4f98ae3cef7c&request_guid=9dd11f11-69d1-4412-8f40-6b7c030185cc&roleName=SYSADMIN": x509: certificate is valid for *.us-west-2.snowflakecomputing.com, *.snowflakecomputing.com, *.global.snowflakecomputing.com, *.prod1.us-west-2.aws.snowflakecomputing.com, *.prod2.us-west-2.aws.snowflakecomputing.com, *.us-west-2.aws.snowflakecomputing.com, not xxxxx.AWS_AP_SOUTHEAST_1.snowflakecomputing.com

Any help please?

**Comment by sfc-gh-bculberson** [comment]
The account and/or region is not set correctly

**Comment by JimMcKenzieSmith** [comment]
@sfc-gh-bculberson I'm getting a similar error.  My account and region are set just fine.  I did notice that the instructions say to use "SELECT current_account(), current_region();" to set the account and region in my bash profile.

current_region() returns AWS_US_WEST_2.

The certificate, as shown by @leeadh, uses dashes and not underscores.  For example "us-west-2" versus "us_west_2".  When I saw what the certificate was expecting, I first tried changing the region from "AWS_US_WEST_2" to "US_WEST_2".  That did not work.  Same error.  Then I tried "US-WEST-2", but then it breaks something else and I get a 403 saying that it fails to connect at all. 

So, in summary, the URL needs underscores to connect (US_WEST_2).  But, the certificate is expecting dashes (US-WEST-2).  I put "ABC123" in for my account for privacy.  What is the fix?
```
Error: error creating database: Post "https://ABC123.US_WEST_2.snowflakecomputing.com:443/session/v1/login-request?requestId=f2594897-2341-470a-bf77-60c91aed1862&request_guid=8c9ee89a-12e7-4841-820c-17062b85f610&roleName=SYSADMIN": x509: 
```
What the cert is valid for:
```
certificate is valid for *.us-west-2.snowflakecomputing.com, *.snowflakecomputing.com, *.global.snowflakecomputing.com, *.prod1.us-west-2.aws.snowflakecomputing.com, *.prod2.us-west-2.aws.snowflakecomputing.com, *.us-west-2.aws.snowflakecomputing.com, 
```
Here is the end of the error which shows the problem:
```
not ABC123.US_WEST_2.snowflakecomputing.com
```

**Comment by JimMcKenzieSmith** [comment]
If anyone else has this problem, I found that the region had to be set to "**us-west-2**".  Then it started working.  The tutorial says to use the output of "SELECT current_region();" which is "AWS_US_WEST_2"... but that does not work.
