### ISSUE TITLE
Bug in Lab setup - Building a data application with Marketplace, Snowpark and Streamlit

### ISSUE THREAD

**Issue by sfc-gh-fgampfer** [Snowflake-Labs/sfquickstarts#544]
**Describe the bug**
This refers to "2. Prepare your lab environment" in "Building a data application with Marketplace, Snowpark and Streamlit"
The lab setup does not work this way and results in an error: ModuleNotFoundError: No module named 'chardet'
This error cannot be fixed easily

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/data_apps_summit_lab/index.html?index=..%2F..index#1

**To Reproduce**
1. Start with a fresh conda environment
2. Follow steps of the quickstart in 2. Prepare your lab environment
3. Execute the first 2 cells of the notebook in 4. Exploring the Data with a (Jupyter) Notebook

**Expected behavior**
No errors when following the steps in the quickstart

**Additional context**
- Tested on MacOS with M1 chip with Python 3.8.13, 3.8.15, 3.8.16 - all result in the same error
- Followed steps outlined here https://docs.snowflake.com/en/developer-guide/snowpark/python/setup#prerequisites to help with M1 chip issues. No improvement

**Potential fix**
Reversing the order of the setup seems to help.
1. conda create --name snowpark -c https://repo.anaconda.com/pkgs/snowflake python=3.8
2. conda activate snowpark
3. conda install snowflake-snowpark-python pandas
4. pip install streamlit
5. pip install -U scikit-learn

**Comment by iamontheinet** [comment]
@sfc-gh-fgampfer Fixed. Basically the packages need to be installed from Snowflake Anaconda channel and I've also added instructions for Apple M1 chip, as well as troubleshooting issues related to pyarrow.

https://quickstarts.snowflake.com/guide/data_apps_summit_lab/index.html?index=..%2F..index#1
