### ISSUE TITLE
Getting Started with SnowSQL - sample data missing

### ISSUE THREAD

**Issue by savirkkula** [Snowflake-Labs/sfquickstarts#59]
Hi, seems that in the guide Getting Started with SnowSQL link to the sample data doesn't' work.

In this page 
https://guides.snowflake.com/guide/getting_started_with_snowsql/index.html?index=..%2F..index#3

i'm getting 404 error with the link Download Sample data
https://docs.snowflake.com/en/_downloads/7f8af74a42c077b86e5bf12cf8ca3247/getting-started.zip

**Comment by gabrielcodingok** [comment]
@sampovirk It happened the same when I tried to download... I found this repository that have similar files, so you can adapt to the tutorial, I don't really know, but for practice I think will work until they update the link in the documentation https://github.com/becloudready/snowflake-tutorials/tree/master/dataset

**Comment by jdanielmyers** [comment]
@sampovirk thanks for letting us know! We are in the process of fixing the link -- stay tuned!
