### ISSUE TITLE
Intermittent Error when running dbt models

### ISSUE THREAD

**Issue by eskim022373** [Snowflake-Labs/sfquickstarts#63]
**Describe the bug**
intermittent  Error:
When runiing dbt run --model +tfm_stock_history_major_currency

Running with dbt=0.19.1
[WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.dbt_hol.l30_mart

Found 7 models, 0 tests, 0 snapshots, 0 analyses, 316 macros, 0 operations, 0 seed files, 2 sources, 0 exposures

Encountered an error:
**Runtime Error
  cannot import name 'SnowflakeOCSPAsn1Crypto' from partially initialized module 'snowflake.connector.ocsp_asn1crypto' (most likely due to a circular import) (c:\snowflake\lab1\dbt-env\lib\site-packages\snowflake\connector\ocsp_asn1crypto.py)**

**URL of where you see the bug**
https://guides.snowflake.com/guide/data_engineering_with_dbt/#7
**To Reproduce**
1. run command:  $ dbt run --model +tfm_stock_history_major_currency
 

**Expected behavior**

Running with dbt=0.19.1
[WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.dbt_hol.l30_mart

Found 7 models, 0 tests, 0 snapshots, 0 analyses, 316 macros, 0 operations, 0 seed files, 2 sources, 0 exposures

21:04:41 | Concurrency: 200 threads (target='dev')
21:04:41 |
21:04:41 | 1 of 6 START view model l10_staging.base_knoema_stock_history........ [RUN]
21:04:41 | 2 of 6 START view model l10_staging.base_knoema_fx_rates............. [RUN]
21:04:44 | 2 of 6 OK created view model l10_staging.base_knoema_fx_rates........ [SUCCESS 1 in 2.62s]
21:04:44 | 3 of 6 START table model l20_transform.tfm_fx_rates.................. [RUN]
21:04:44 | 1 of 6 OK created view model l10_staging.base_knoema_stock_history... [SUCCESS 1 in 2.69s]
21:04:44 | 4 of 6 START view model l20_transform.tfm_knoema_stock_history....... [RUN]
21:04:46 | 4 of 6 OK created view model l20_transform.tfm_knoema_stock_history.. [SUCCESS 1 in 2.41s]
21:04:46 | 5 of 6 START view model l20_transform.tfm_stock_history.............. [RUN]
21:04:49 | 5 of 6 OK created view model l20_transform.tfm_stock_history......... [SUCCESS 1 in 2.47s]
21:04:52 | 3 of 6 OK created table model l20_transform.tfm_fx_rates............. [SUCCESS 1 in 7.91s]
21:04:52 | 6 of 6 START view model l20_transform.tfm_stock_history_major_currency [RUN]
21:04:55 | 6 of 6 OK created view model l20_transform.tfm_stock_history_major_currency [SUCCESS 1 in 2.79s]
21:04:56 |
21:04:56 | Finished running 5 view models, 1 table model in 19.96s.

Completed successfully

Done. PASS=6 WARN=0 ERROR=0 SKIP=0 TOTAL=6

**Screenshots**
![image](https://user-images.githubusercontent.com/85598690/121287326-8e235400-c89e-11eb-9052-5d03619f60ad.png)

**Additional context**
rerunning the prevevous model from step 6 seemed  help.. but not sure why
![image](https://user-images.githubusercontent.com/85598690/121287450-cdea3b80-c89e-11eb-994c-4b998acceb42.png)

**Comment by eskim022373** [comment]
Also seem to happen when dbt run  (again it intermittent)  but it seem to fail more that work

**Comment by eskim022373** [comment]
This seem be realted to my install

  Building wheel for tree-sitter (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\snowflake\lab1\dbt2\scripts\python.exe' 'c:\snowflake\lab1\dbt2\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\eskim\AppData\Local\Temp\tmpxclxl9z_' 
       cwd: C:\Users\eskim\AppData\Local\Temp\pip-install-ct586pwj\tree-sitter_f722a907dbad4e07b56a4e7839cd794a
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\tree_sitter
  copying tree_sitter\__init__.py -> build\lib.win-amd64-3.9\tree_sitter
  running build_ext
  building 'tree_sitter.binding' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for tree-sitter
Failed to build tree-sitter
ERROR: Could not build wheels for tree-sitter which use PEP 517 and cannot be installed directly

**Comment by yarodmi** [comment]
hi @eskim022373,
Thanks for reaching out. I do agree, this does look like an issue related to the local configuration rather than a lab or dbt itself. 
If thats possible, I would suggest updating your python/python driver (https://docs.snowflake.com/en/release-notes/requirements.html) and if that still remain unstable, raise a support case with Snowflake support to troubleshoot in a greater details. 
Hope this helps
