### ISSUE TITLE
invoke_model function takes 3 arguments. 

### ISSUE THREAD

**Issue by sfc-gh-pjain** [Snowflake-Labs/sfquickstarts#69]
**Describe the bug**
Invoke model function takes 3 arguments, please update the select statement for real time predictions.
**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/recommendation_engine_aws_sagemaker/index.html?index=..%2F..index#11

**To Reproduce**
check the last SQL on this page .

select nr.USERID, nr.MOVIEID, m.title, **invoke_model(nr.USERID,nr.MOVIEID)** as rating_prediction
from no_ratings nr, movies m
where nr.movieid = m.movieid;

**Expected behavior**

select nr.USERID, nr.MOVIEID, m.title, **invoke_model('<model name>',nr.USERID,nr.MOVIEID)** as rating_prediction
from no_ratings nr, movies m
where nr.movieid = m.movieid;

**Screenshots**
![image](https://user-images.githubusercontent.com/81378216/122943441-0715b780-d345-11eb-98b2-65983cebc858.png)

**Comment by sfc-gh-jwest** [comment]
Working on this now
