### ISSUE TITLE
Getting Started With User-Defined Functions: using ACCOUNTADMIN role not required

### ISSUE THREAD

**Issue by sfc-gh-mabrennan** [Snowflake-Labs/sfquickstarts#70]
In the tutorial Getting Started With User-Defined Functions, on page https://quickstarts.snowflake.com/guide/getting_started_with_user_defined_functions/index.html#1 
it says: "Switch the account role from the default SYSADMIN to ACCOUNTADMIN.". I'm pretty sure this isn't required. I was able to finish the tutorial using just the SYSADMIN role. 

**URL of where you see the bug**
https://quickstarts.snowflake.com/guide/getting_started_with_user_defined_functions/index.html#1

**Comment by sfc-gh-jwest** [comment]
May not be required, but it works.
