### ISSUE TITLE
Download Sample Data button not working(gives 404 error)

### ISSUE THREAD

**Issue by sfc-gh-smishra** [Snowflake-Labs/sfquickstarts#71]
Hi Team,

The "Download Sample Data" button [here](https://quickstarts.snowflake.com/guide/getting_started_with_snowsql/index.html?index=..%2F..index#3) is not working and gives us "404 not found error". Can you please help fix the link?

Snowflake Guide in Question : Getting Started with SnowSQL

**Comment by sfc-gh-jwest** [comment]
Fixed
