### ISSUE TITLE
invoke_model function with remote service error 400

### ISSUE THREAD

**Issue by kezhuguo** [Snowflake-Labs/sfquickstarts#73]
**Describe the bug**
Following the "Build a Recommendation Engine with AWS SageMaker" instructions, and at the last step of calling the nvoke_model function, I got the error message:
Request failed for external function INVOKE_MODEL with remote service error: 400 'list index out of range'; requests batch-id: 019d281f-0400-c93b-0053-30830001f57e:0:1; request batch size: 2 rows; request retries: 0; response time (last retry): 66.92ms
Not sure how to resolve it...

**URL of where you see the bug**
[https://quickstarts.snowflake.com/guide/recommendation_engine_aws_sagemaker/index.html?index=..%2F..index#11](url)

**To Reproduce**
select nr.USERID, nr.MOVIEID, m.title, **invoke_model(nr.USERID,nr.MOVIEID)** as rating_prediction
from no_ratings nr, movies m
where nr.movieid = m.movieid;

**Comment by sfc-gh-jwest** [comment]
@kezhuguo was your end point fully deployed? Deploying an endpoint will take some time as well, perhaps 15 minutes or so. You can check the Endpoints tab within the SageMaker console to view the endpoint's status.  The endpoint will be fully deployed when its status is "In Service."
