### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by sfc-gh-mabrennan** [Snowflake-Labs/sfquickstarts#78]
**Describe the bug**
Here is a list of several broken links in various quick start guides.

**URL of where you see the bug**

Web page | Broken Link
-- | --
https://quickstarts.snowflake.com/guide/security_network_architecture_pattern/index.html#3 | https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html%23what-is-privatelink&sa=D&ust=1608660555649000&usg=AOvVaw1Q1lpnr0FYZf_X3kHthIya
https://quickstarts.snowflake.com/guide/security_network_architecture_pattern/index.html#4 | https://docs.microsoft.com/en-us/azure/private-link/private-link-overview&sa=D&ust=1608660555650000&usg=AOvVaw2BGDTLXGqLToQI-Svcljfh
https://quickstarts.snowflake.com/guide/vhol_fivetran/index.html#2 | https://fivetran.com/dashboard
https://quickstarts.snowflake.com/guide/sample/index.html#0 | https://raw.githubusercontent.com/Snowflake-Labs/sfguides/master/site/sfguides/sample.md
https://quickstarts.snowflake.com/guide/sample/index.html | https://raw.githubusercontent.com/Snowflake-Labs/sfguides/master/site/sfguides/sample.md
https://quickstarts.snowflake.com/guide/sample/index.html | https://raw.githubusercontent.com/Snowflake-Labs/sfguides/master/site/sfguides/sample.md
https://quickstarts.snowflake.com/guide/sample/index.html | https://raw.githubusercontent.com/Snowflake-Labs/sfguides/master/site/sfguides/sample.md
https://quickstarts.snowflake.com/guide/vhol_data_marketplace_app/index.html#0 | https://download
https://quickstarts.snowflake.com/guide/vhol_data_marketplace_app/index.html#3 | https://github.com/brenStokes/Building-an-App-with-Data-Marketplace-/tree/main/quasar
https://quickstarts.snowflake.com/guide/vhol_data_marketplace_app/index.html#4 | https://github.com/brenStokes/Building-an-App-with-Data-Marketplace-/tree/main/Lambda-src
https://quickstarts.snowflake.com/guide/vhol_data_marketplace_app/index.html#4 | https://github.com/brenStokes/Building-an-App-with-Data-Marketplace-/tree/main/Lambda-src

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the page in the first column of the table.
2. Right-click the web page and select "view source".
3. Search for the URL in the 2nd column.
4. Go back to the page and click the link.

**Comment by jdanielmyers** [comment]
These links have been updated -- thank you!
