### ISSUE TITLE
"What we covered" section is incorrect on the last page

### ISSUE THREAD

**Issue by sfc-gh-sdickson** [Snowflake-Labs/sfquickstarts#88]
What We've Covered
Data Loading: Load Twitter streaming data in an event-driven, real-time fashion into Snowflake with Snowpipe
Semi-structured data: Querying semi-structured data (JSON) without needing transformations
Secure Views: Create a Secure View to allow data analysts to query the data
Snowpipe: Overview and configuration

We used Snowpark(Scala) and loaded a CSV file to perform sentiment analysis on sample tweet data.  I recommend changing to:

What We've Covered
Data Loading: Load Twitter data into Snowflake with Snowpark(Scala)
Data: Created a data frame from the CSV file and removed unwanted columns
Sentiment Analysis: Showed how to use Scala to perform sentiment analysis on a data frame of tweets
Snowpark: Used Scala to write the data frame into a Snowflake table

.....or something like this

**Comment by jdanielmyers** [comment]
Thank you - fixed!
