### ISSUE TITLE
Step 9 did not work correctly

### ISSUE THREAD

**Issue by sfc-mradalj** [Snowflake-Labs/sfquickstarts#89]
Step 9 was supposed to alter a table and add a column. This is being skipped when I manually execute the Jenkins pipeline. I have the correct ./migration files.

**This is the URL of my Jenkins GUI**
URL: http://localhost:8080/job/snowflake-devops-demo/

**To Reproduce**

1. Go to Jenkins Dashboard showing pipeline.
2. click on the Build with Parameters option in the left navigation bar. 
3. Verify that all the parameter values look correct and click on the blue Build button to start the Pipeline.
4. See the logs.

 
**Expected behavior**
I expected the logs to have applied the latest changes in file V1.1.2__new_objects.sql. But it skipped this step. No errors. Just skipping, nothing to be done.

**Screenshots**
<img width="934" alt="image" src="https://user-images.githubusercontent.com/84107609/128386233-ce9609bb-ff65-42f6-aabc-8952cb3215f2.png">

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/84107609/128386286-f5036834-9a44-4fab-a676-0dfdd13c7930.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur Version 11.5
 - Browser: Chrome
 - Version: Chrome version Version 92.0.4515.107 (Official Build) (x86_64)

**Additional context**
When I restarted the Docker image, I now get build errors.

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/84107609/128386781-a78d09d2-88dc-4401-8c05-d44af696ece2.png">

<img width="1781" alt="image" src="https://user-images.githubusercontent.com/84107609/128387002-cb99886a-6610-43dc-be7d-ad5fe3b05eb3.png">

**Comment by sfc-mradalj** [comment]
Never mind what I wrote about builds failing. I figured out when I restart docker image, I have to run on the command line:

mradalj@C02F33KCMD6R migrations % docker exec -it -u root jenkins bash -c 'chmod 666 /var/run/docker.sock'

However, I still get the no-op running the pipeline. The alter table to add a column never gets applied.

**Comment by sfc-gh-jhansen** [comment]
Hi there @sfc-mradalj, thanks for going through this Quickstart and pointing out this issue. I have updated the Quickstart to include instructions on how to avoid this. In particular, please see the new "Additional Behaviours" setting under the "Creating the Jenkins Pipeline" section on step 6. Once you enable that your Jenkins pipeline will clone your repo on every execution.
