### ISSUE TITLE
lab_scripts.sql file missing

### ISSUE THREAD

**Issue by christyvp** [Snowflake-Labs/sfquickstarts#96]
In section 3 it says "Browse to the lab_scripts.sql file you downloaded in the previous section and select Open." But there was nowhere to download this in the previous section.

**Comment by sohnya** [comment]
any news on where I can find this SQL script? Looks like the whole lab is built on it.

**Comment by christyvp** [comment]
@jdanielmyers can someone from snowflake look into this, my trial is almost up and I'd like to complete the lab. TIA!

**Comment by sfc-gh-jwest** [comment]
@christyvp which lab are you referring to?

**Comment by sfc-gh-jwest** [comment]
Found it.  Sorry for the confusion, the script is not needed.  The SQL statements can be copied and pasted from each step.
